
services:
  app:
    image: thecodingmachine/php:8.2-v4-cli
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      QUEUE_CONNECTION: database
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -lc "rm -f storage/framework/.migrated && until php -r \"mysqli_report(MYSQLI_REPORT_OFF); exit((int)!@mysqli_connect(getenv('DB_HOST'), getenv('DB_USERNAME'), getenv('DB_PASSWORD'), null, (int)(getenv('DB_PORT') ?: 3306)));\"; do sleep 2; done && composer install && php artisan key:generate --force && php artisan migrate --force && touch storage/framework/.migrated && php artisan serve --host=0.0.0.0 --port=8000"

  queue:
    image: thecodingmachine/php:8.2-v4-cli
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      QUEUE_CONNECTION: database
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    command: >
      bash -lc "while [ ! -f vendor/autoload.php ]; do sleep 2; done; while [ ! -f storage/framework/.migrated ]; do sleep 2; done; php artisan queue:work --verbose --tries=3 --timeout=90"

  scheduler:
    image: thecodingmachine/php:8.2-v4-cli
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      QUEUE_CONNECTION: database
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    command: >
      bash -lc "while [ ! -f vendor/autoload.php ]; do sleep 2; done; while [ ! -f storage/framework/.migrated ]; do sleep 2; done; while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
