services:
  app:
    build:
      target: development
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      LOG_LEVEL: debug
      CACHE_STORE: file
      SESSION_DRIVER: file
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          php -r "new PDO('mysql:host=' . getenv('DB_HOST') . ';port=' .
          getenv('DB_PORT') . ';dbname=' . getenv('DB_DATABASE'),
          getenv('DB_USERNAME'), getenv('DB_PASSWORD'));"

  queue:
    build:
      target: development
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      LOG_LEVEL: debug
      CACHE_STORE: file
      SESSION_DRIVER: file

  scheduler:
    build:
      target: development
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      LOG_LEVEL: debug
      CACHE_STORE: file
      SESSION_DRIVER: file

  frontend:
    environment:
      VITE_API_URL: '${VITE_API_URL:-http://localhost:8080}'
